// translation_es.h -- ES TRANSLATION HOOK (F5) for Infinite Undiscovery (recomp).
//
// Mechanism: ReXGlue uses weak aliases.  We replace (strong symbol) the message
// directory parser `sub_826D52C0`, call the original via
// `__imp__sub_826D52C0` and, if the message (bank,id) has a translation, replace
// the resolved text pointer (`obj+0x78`) with our own buffer in guest memory
// holding the already-encoded ES codes (scheme b0/b1; see docs/re/font-loader.md).
//
// The bank is identified by the SIGNATURE of the loaded `.msg` header
// (`total,count,atlas_w,atlas_h`), which the parser has in `obj+0x64`.
//
// CATALOG: `translation/es_catalog.bin` (generated by tools/gen_es_catalog.py):
//   u32 magic 'IUC1', u32 n, and n blocks:
//     u32 total,count,atlas_w,atlas_h,id,ncodes ; u16 codes[ncodes]
//
// Include ONCE only from src/main.cpp.

#pragma once

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <rex/ppc/context.h>
#include <rex/system/kernel_state.h>
#include <rex/system/xmemory.h>

#include "iu_trace.h"
// Generic TEXTURE substitution (bitmap labels).  Extends FindAtlasOnce to
// all the textures in the manifest `translation/ui_textures.txt`.
#include "ui_textures_es.h"
// Spanish accent patch PER BANK (WS1): applies the enlarged atlas of
// each `RMD-` from `translation/accents_atlas.bin` when its `.msg` is loaded.
#include "accents_es.h"
// Mod options exposed as CVARs: es_translation, es_textures, es_catalog,
// es_textures_manifest.
#include "translation_cvars.h"
// Translates the .exe's zone-name table (MapName) at runtime (option D).
#include "zone_names_es.h"

// Options saved by the setup wizard (portable_setup.cpp).
namespace iu::portable {
bool EsTranslation();
bool EsTextures();
}  // namespace iu::portable

namespace iu::translation {

using Codes = std::vector<uint16_t>;

inline uint32_t rd32(uint8_t* base, uint32_t g) {
  return __builtin_bswap32(*reinterpret_cast<volatile uint32_t*>(iu::trace::host_ptr(base, g)));
}
inline void wr32(uint8_t* base, uint32_t g, uint32_t v) {
  *reinterpret_cast<volatile uint32_t*>(iu::trace::host_ptr(base, g)) = __builtin_bswap32(v);
}

inline uint32_t FpHash(uint32_t total, uint32_t count, uint32_t aw, uint32_t ah) {
  uint32_t h = 2166136261u;
  auto mix = [&](uint32_t v) {
    h ^= v;
    h *= 16777619u;
  };
  mix(total);
  mix(count);
  mix(aw);
  mix(ah);
  return h;
}

inline bool Enabled() {
  static const bool e = []() {
    // Priority: CVAR (CLI/config/console) > environment > wizard > default.
    if (rex::cvar::GetFlagSource("es_translation") != rex::cvar::Source::kDefault)
      return iu::tr::ParseBool(rex::cvar::GetFlagByName("es_translation"), true);
    const char* v = std::getenv("IU_ES");
    if (v && v[0]) return v[0] != '0';
    return iu::portable::EsTranslation();
  }();
  return e;
}

inline std::string CatalogPath() {
  static const std::string p = iu::tr::EsCatalog();
  return p;
}

struct Catalog {
  bool loaded = false;
  std::unordered_map<uint32_t, std::unordered_map<uint32_t, Codes>> by_fp;
  std::unordered_map<uint64_t, uint32_t> cache;  // fp:id -> guest addr (0 = no translation)
  size_t n_strings = 0;
};

inline Catalog& catalog() {
  static Catalog c;
  return c;
}

inline void LoadCatalog() {
  Catalog& c = catalog();
  if (c.loaded) return;
  c.loaded = true;
  std::FILE* f = std::fopen(CatalogPath().c_str(), "rb");
  if (!f) {
    iu::trace::emit(iu::trace::kGeneral, "ES: catalogo ausente (%s)", CatalogPath().c_str());
    return;
  }
  uint32_t magic = 0, n = 0;
  if (std::fread(&magic, 4, 1, f) != 1 || std::fread(&n, 4, 1, f) != 1 || magic != 0x31435549u) {
    std::fclose(f);
    iu::trace::emit(iu::trace::kGeneral, "ES: catalogo invalido");
    return;
  }
  for (uint32_t i = 0; i < n; ++i) {
    uint32_t hdr[6];
    if (std::fread(hdr, 4, 6, f) != 6) break;
    Codes cs(hdr[5]);
    if (hdr[5] && std::fread(cs.data(), 2, hdr[5], f) != hdr[5]) break;
    c.by_fp[FpHash(hdr[0], hdr[1], hdr[2], hdr[3])][hdr[4]] = std::move(cs);
    ++c.n_strings;
  }
  std::fclose(f);
  iu::trace::emit(iu::trace::kGeneral, "ES: catalogo cargado: %zu cadenas, %zu bancos", c.n_strings,
                  c.by_fp.size());
}

// ---- byte-stream codec ----
inline Codes DecodeStream(uint8_t* base, uint32_t g) {
  Codes out;
  if (g < 0x10000u || !iu::trace::readable(base, g, 1)) return out;
  uint8_t* p = iu::trace::host_ptr(base, g);
  for (int guard = 0; guard < 200000; ++guard) {
    uint8_t b0 = *p++;
    if (b0 == 0) break;
    uint16_t code;
    if (b0 & 0x80) {
      uint8_t b1 = *p++;
      code = static_cast<uint16_t>((b1 << 7) | (b0 & 0x7F));
    } else {
      code = b0;
    }
    out.push_back(code);
  }
  return out;
}

inline std::vector<uint8_t> EncodeStream(const Codes& codes) {
  std::vector<uint8_t> out;
  out.reserve(codes.size() * 2 + 1);
  for (uint16_t c : codes) {
    if (c == 0) {
      out.push_back(0);
    } else if (c < 0x80) {
      out.push_back(static_cast<uint8_t>(c));
    } else {
      out.push_back(static_cast<uint8_t>((c & 0x7F) | 0x80));
      out.push_back(static_cast<uint8_t>(c >> 7));
    }
  }
  out.push_back(0);
  return out;
}

inline uint32_t AllocAndWrite(uint8_t* base, const Codes& codes) {
  std::vector<uint8_t> bytes = EncodeStream(codes);
  auto* mem = rex::system::kernel_memory();
  if (!mem) {
    iu::trace::emit(iu::trace::kGeneral, "ES: kernel_memory nulo");
    return 0;
  }
  uint32_t g = mem->SystemHeapAlloc(static_cast<uint32_t>(bytes.size()), 0x20);
  if (!g) {
    iu::trace::emit(iu::trace::kGeneral, "ES: SystemHeapAlloc(%zu) fallo", bytes.size());
    return 0;
  }
  // Write through the SAME path the reader uses (base + guest + offset).
  std::memcpy(iu::trace::host_ptr(base, g), bytes.data(), bytes.size());
  return g;
}

inline bool IsMsg(uint8_t* base, uint32_t g) {
  return g >= 0x10000u && iu::trace::readable(base, g, 0x68) && rd32(base, g) == 0x4D657373u;
}

// ---- text width ------------------------------------------------------------
// The engine stores in `obj+0xC4` the RESOLVED width of the message (f32 BE,
// copied from the `.msg` record, computed on the ENGLISH text).  Some screens
// (e.g. the `~ <title> ~` CAMP header) CENTER the title using that width; if
// the English one is kept, a shorter ES title ("Equipo" vs "Equipment") shifts
// to the left and the closing `~` ornament ends up far away.  Here we
// recompute the width of the ES text.
//
// Each glyph's metric (`.msg` `metrics_off` table, 1 byte) is its advance; the
// real width scales with the sum of metrics (the record also applies a constant
// kerning factor ~0.87, which cancels out when scaling by the ES/EN ratio).
// So: width_ES = width_EN * (sum_ES / sum_EN).
inline float rd_f32(uint8_t* base, uint32_t g) {
  uint32_t v = rd32(base, g);
  float f;
  std::memcpy(&f, &v, 4);
  return f;
}
inline void wr_f32(uint8_t* base, uint32_t g, float f) {
  uint32_t v;
  std::memcpy(&v, &f, 4);
  wr32(base, g, v);
}

inline uint32_t MetricSum(uint8_t* base, uint32_t msgbase, const Codes& codes) {
  if (!IsMsg(base, msgbase)) return 0;
  uint32_t mo = rd32(base, msgbase + 0x28);
  if (!mo) return 0;
  uint32_t s = 0;
  for (uint16_t c : codes) {
    if (c >= 300 && c < 0x4000) {
      uint32_t off = msgbase + mo + 2u * (c - 301);
      if (iu::trace::readable(base, off, 1))
        s += *reinterpret_cast<volatile uint8_t*>(iu::trace::host_ptr(base, off));
    }
  }
  return s;
}

// Adjusts `obj+0xC4` (and the `.msg` record width) to the substituted text.
// Only for short texts (centered labels/headers); long dialogues are not
// centered and do not need it.
inline void FixWidth(uint8_t* base, uint32_t obj, uint32_t msgbase, uint32_t orig_text,
                     uint32_t id, const Codes& es) {
  if (es.size() > 24) return;
  if (!IsMsg(base, msgbase)) return;
  Codes en = DecodeStream(base, orig_text);
  uint32_t s_en = MetricSum(base, msgbase, en);
  uint32_t s_es = MetricSum(base, msgbase, es);
  if (!s_en || !s_es) return;
  float rec_w = rd_f32(base, obj + 0xC4);
  if (!(rec_w > 0.0f)) return;
  float w_es = rec_w * static_cast<float>(s_es) / static_cast<float>(s_en);
  wr_f32(base, obj + 0xC4, w_es);
  // `.msg` record (id -> offset, width, height): update the width.
  uint32_t rec_off = rd32(base, msgbase + 0x20);
  if (!rec_off || !iu::trace::readable(base, msgbase + rec_off, 16)) return;
  uint32_t rec = msgbase + rec_off;
  for (int i = 0; i < 200000; ++i) {
    uint32_t A = rd32(base, rec);
    uint32_t B = rd32(base, rec + 4);
    if (A == 0 && B == 0) break;
    if (A == id) {
      wr_f32(base, rec + 8, w_es);
      iu::trace::emit(iu::trace::kGeneral, "ES: ancho id=%u %.1f -> %.1f", id,
                      static_cast<double>(rec_w), static_cast<double>(w_es));
      return;
    }
    rec += 16;
  }
}

// Replaces the atlas (4 198 400 B, same size) with ours from the file.
inline bool ReplaceAtlas(uint8_t* base, uint32_t g, const char* path) {
  std::FILE* f = std::fopen(path, "rb");
  if (!f) {
    iu::trace::emit(iu::trace::kGeneral, "ES: no abro %s", path);
    return false;
  }
  static std::vector<uint8_t> buf;
  buf.clear();
  uint8_t tmp[65536];
  size_t n;
  while ((n = std::fread(tmp, 1, sizeof(tmp), f)) > 0) buf.insert(buf.end(), tmp, tmp + n);
  std::fclose(f);
  const uint32_t need = 4198400u;
  if (buf.size() != need) {
    iu::trace::emit(iu::trace::kGeneral, "ES: atlas ES tiene %zu (esperado %u)", buf.size(), need);
    return false;
  }
  std::memcpy(iu::trace::host_ptr(base, g), buf.data(), need);
  iu::trace::emit(iu::trace::kGeneral, "ES atlas SUSTITUIDO @ %08X (%u bytes)", g, need);
  return true;
}

// Searches guest memory for the UI atlas (raw AIF) by its signature and REPLACES it.
inline uint32_t FindAtlasOnce(uint8_t* base) {
  static const uint8_t P[36] = {
      0x41, 0x49, 0x46, 0x20, 0x00, 0x40, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x69, 0x6D, 0x67, 0x58, 0x00, 0x00, 0x00, 0x70,
      0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50, 0x47, 0x30, 0x32};
  for (uint32_t g = 0x80000000u; g < 0xF0000000u; g += 0x1000u) {
    uint8_t* p = iu::trace::host_ptr(base, g);
    MEMORY_BASIC_INFORMATION mbi;
    if (!VirtualQuery(p, &mbi, sizeof(mbi))) continue;
    if (mbi.State != MEM_COMMIT) continue;
    if (mbi.Protect & (PAGE_NOACCESS | PAGE_GUARD)) continue;
    for (size_t i = 0; i + 36 <= 0x1000; ++i) {
      if (p[i] == 0x41 && std::memcmp(p + i, P, 36) == 0) {
        uint32_t addr = g + (uint32_t)i;
        iu::trace::emit(iu::trace::kGeneral, "ES SCAN atlas @ %08X", addr);
        ReplaceAtlas(base, addr, "translation/atlas_ui_es.aif");
        return addr;
      }
    }
  }
  iu::trace::emit(iu::trace::kGeneral, "ES SCAN atlas NO encontrado");
  return 0;
}

inline void TrySubstitute(uint8_t* base, uint32_t obj) {
  if (!Enabled()) return;
  if (obj < 0x10000u) return;
  // Per-OBJECT cache: if the id did not change, reapply the buffer without
  // re-reading headers or doing VirtualQuery (this is what ran every frame and
  // slowed things down).
  static std::unordered_map<uint32_t, std::pair<uint32_t, uint32_t>> objc;
  uint32_t id = rd32(base, obj + 0x88);
  auto oit = objc.find(obj);
  if (oit != objc.end() && oit->second.first == id) {
    if (oit->second.second) wr32(base, obj + 0x78, oit->second.second);
    return;
  }
  if (!iu::trace::readable(base, obj, 0x90)) return;
  // Large font (obj+0x64, codes >= 300) or small (obj+0x60, codes < 300).
  uint32_t mb_large = rd32(base, obj + 0x64);
  uint32_t mb_small = rd32(base, obj + 0x60);
  uint32_t msgbase = IsMsg(base, mb_large) ? mb_large : (IsMsg(base, mb_small) ? mb_small : 0);
  if (!msgbase) {
    objc[obj] = {id, 0};
    return;
  }

  // Textures bound to the `.msg` (RMD- fonts: accents 005) + preceding atlas.
  iu::ui::OnMsg(base, msgbase);
  // Spanish accents per bank (WS1): patches the RMD- atlas of THIS bank
  // (aif = msgbase - aif_size) and the `.msg` metric table.
  iu::accents::OnMsg(base, msgbase);

  uint32_t total = rd32(base, msgbase + 0x30);
  uint32_t count = rd32(base, msgbase + 0x34);
  uint32_t aw = rd32(base, msgbase + 0x60);
  uint32_t ah = rd32(base, msgbase + 0x64);
  uint32_t fp = FpHash(total, count, aw, ah);
  uint64_t key = (static_cast<uint64_t>(fp) << 32) | id;

  Catalog& c = catalog();
  auto it = c.cache.find(key);
  if (it != c.cache.end()) {
    if (it->second) wr32(base, obj + 0x78, it->second);
    return;
  }

  Codes codes;
  bool found = false;
  auto fpit = c.by_fp.find(fp);
  if (fpit != c.by_fp.end()) {
    auto idit = fpit->second.find(id);
    if (idit != fpit->second.end()) {
      codes = idit->second;
      found = true;
    }
  }
  if (!found) {
    c.cache[key] = 0;
    return;
  }
  // Adjust the RESOLVED WIDTH to the ES text (centered headers, e.g. the
  // `~ <title> ~` of the CAMP).  Done BEFORE overwriting obj+0x78.
  FixWidth(base, obj, msgbase, rd32(base, obj + 0x78), id, codes);
  uint32_t g = AllocAndWrite(base, codes);
  c.cache[key] = g;
  objc[obj] = {id, g};
  if (g) wr32(base, obj + 0x78, g);
}

}  // namespace iu::translation

// Strong override of the message directory parser.
extern "C" void __imp__sub_826D52C0(PPCContext& ctx, uint8_t* base);
extern "C" void sub_826D52C0(PPCContext& ctx, uint8_t* base) {
  const uint32_t obj = ctx.r3.u32;  // capture BEFORE: on return, r3 = return value
  __imp__sub_826D52C0(ctx, base);
  iu::translation::ZoneNamesStart(base);
  iu::translation::LoadCatalog();
  iu::translation::TrySubstitute(base, obj);
  // Persistent textures by SIGNATURE (UI atlas, GAME OVER, Now Loading, Reload...).
  // `Tick` starts (once) the THREAD that searches for them; the game is not blocked.
  static const bool want_scan = []() {
    // Priority: CVAR > environment > wizard > default (enabled).
    if (rex::cvar::GetFlagSource("es_textures") != rex::cvar::Source::kDefault)
      return iu::tr::ParseBool(rex::cvar::GetFlagByName("es_textures"), true);
    const char* e = std::getenv("IU_ES_SCAN");
    if (e && e[0]) return e[0] != '0';
    return iu::portable::EsTextures();
  }();
  if (want_scan) iu::ui::Tick(base);
}
